### TOGGLE FOLLOW USER
POST http://localhost:4201/toggleFollowUser
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJEYW5pZWwiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJ1c2VyX2lkIjoiYmQxNTk5M2ItZjFkNS00YTQ0LThkNWQtN2Q5Zjc1ZDVkM2E0IiwiaXNBZG1pbiI6ZmFsc2UsImZ1bGxOYW1lIjoiRGFuaWVsIEthc2VlIiwiaWF0IjoxNzAyNzE2MDYwLCJleHAiOjE3MDI4MDI0NjB9.Cldvkdvp8ngEtGNg9YMqGF_F7raZX3hVFSjBsyRxtDk
Content-Type: application/json

{
   "follower_user_id":"c089ca87-4af2-4a5c-8721-894aa0611e00", 
   "followed_user_id":"bd15993b-f1d5-4a44-8d5d-7d9f75d5d3a4"
}

#### get followers
GET http://localhost:4201/getFollowers/c089ca87-4af2-4a5c-8721-894aa0611e00
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJEYW5pZWwiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJ1c2VyX2lkIjoiYmQxNTk5M2ItZjFkNS00YTQ0LThkNWQtN2Q5Zjc1ZDVkM2E0IiwiaXNBZG1pbiI6ZmFsc2UsImZ1bGxOYW1lIjoiRGFuaWVsIEthc2VlIiwiaWF0IjoxNzAyNzE2MDYwLCJleHAiOjE3MDI4MDI0NjB9.Cldvkdvp8ngEtGNg9YMqGF_F7raZX3hVFSjBsyRxtDk



### GET FOLLOWINGS
GET http://localhost:4201/getFollowings/c089ca87-4af2-4a5c-8721-894aa0611e00
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJEYW5pZWwiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJ1c2VyX2lkIjoiYmQxNTk5M2ItZjFkNS00YTQ0LThkNWQtN2Q5Zjc1ZDVkM2E0IiwiaXNBZG1pbiI6ZmFsc2UsImZ1bGxOYW1lIjoiRGFuaWVsIEthc2VlIiwiaWF0IjoxNzAyNzE2MDYwLCJleHAiOjE3MDI4MDI0NjB9.Cldvkdvp8ngEtGNg9YMqGF_F7raZX3hVFSjBsyRxtDk


#### FOLLOWING POSTS --skip
GET http://localhost:4201/followingPosts/c089ca87-4af2-4a5c-8721-894aa0611e00
token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJEYW5pZWwiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJ1c2VyX2lkIjoiYmQxNTk5M2ItZjFkNS00YTQ0LThkNWQtN2Q5Zjc1ZDVkM2E0IiwiaXNBZG1pbiI6ZmFsc2UsImZ1bGxOYW1lIjoiRGFuaWVsIEthc2VlIiwiaWF0IjoxNzAyNzE2MDYwLCJleHAiOjE3MDI4MDI0NjB9.Cldvkdvp8ngEtGNg9YMqGF_F7raZX3hVFSjBsyRxtDk