## CREATE POST

POST http://localhost:4201/post/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJTYW5ueSIsImVtYWlsIjoiZW1tYW51ZWxAZ21haWwuY29tIiwidXNlcl9pZCI6ImI0YzFjMzIwLTM5YTgtNDQ3MS1hYWRkLTQ5NTZjZTMwNDhkNSIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vaW1hZ2VzLnVuc3BsYXNoLmNvbS9waG90by0xNTE4MDIwMzgyMTEzLWE3ZThmYzM4ZWFjOT9xPTgwJnc9MTQzNCZhdXRvPWZvcm1hdCZmaXQ9Y3JvcCZpeGxpYj1yYi00LjAuMyZpeGlkPU0zd3hNakEzZkRCOE1IeHdhRzkwYnkxd1lXZGxmSHg4ZkdWdWZEQjhmSHg4ZkElM0QlM0QiLCJmdWxsTmFtZSI6IkVtbWFudWVsIGtpcHNhbmciLCJpYXQiOjE3MDMwMzQzODEsImV4cCI6MTcwMzEyMDc4MX0.fdA11mebDEmiN9gLoE8N1ktAZ1UMc_WSiKz6uUVJ3UQ
Content-Type: application/json

{
    "created_by_user_id":"b4c1c320-39a8-4471-aadd-4956ce3048d5",
    "caption":"Posted"    
   
}

### CREATE POST WITH IMAGE
POST http://localhost:4201/post/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJTYW5ueSIsImVtYWlsIjoiZW1tYW51ZWxAZ21haWwuY29tIiwidXNlcl9pZCI6ImI0YzFjMzIwLTM5YTgtNDQ3MS1hYWRkLTQ5NTZjZTMwNDhkNSIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vaW1hZ2VzLnVuc3BsYXNoLmNvbS9waG90by0xNTE4MDIwMzgyMTEzLWE3ZThmYzM4ZWFjOT9xPTgwJnc9MTQzNCZhdXRvPWZvcm1hdCZmaXQ9Y3JvcCZpeGxpYj1yYi00LjAuMyZpeGlkPU0zd3hNakEzZkRCOE1IeHdhRzkwYnkxd1lXZGxmSHg4ZkdWdWZEQjhmSHg4ZkElM0QlM0QiLCJmdWxsTmFtZSI6IkVtbWFudWVsIGtpcHNhbmciLCJpYXQiOjE3MDMwMzM5NTcsImV4cCI6MTcwMzEyMDM1N30.03m6QxZ4yfGVVdUtKJgE8i-8Irpia1CHHd9G4Yn1CUs
Content-Type: application/json

{
    "postImage":"https://i.ebayimg.com/images/g/rOQAAOSwOWhhuxOJ/s-l1200.webp",
    "created_by_user_id":"b4c1c320-39a8-4471-aadd-4956ce3048d5",
    "caption":"Posted"   
}


### update a post 

PUT http://localhost:4201/post/
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiJmODNjZjQ3MC0xYjc1LTQ0ZWMtYWRiNy03ZDZjMGRlZWJkOGIiLCJpc0FkbWluIjpmYWxzZSwiZnVsbE5hbWUiOiJEaWFuYSBhYmVyaSIsImlhdCI6MTcwMjU4NjM0NSwiZXhwIjoxNzAyNjcyNzQ1fQ.q2f4tcavzwXBuyMrmusb7dioZ2oM3PqhzIQNkdXJHLA
Content-Type: application/json

{
    "UpdatedPostImage":["https://c4.wallpaperflare.com/wallpaper/193/556/883/car-neon-chevrolet-corvette-race-cars-hd-wallpaper-preview.jpg","https://w0.peakpx.com/wallpaper/135/1018/HD-wallpaper-car-sports-car-neon-backlight-asphalt.jpg"],
    "updatedCaption":"This is my first edit of caption",
    "post_id" : "863b5dcd-f2a7-4105-8ba1-9a96c8a2c396",
     "updated_at" : "now"
}

### DELETE POST
DELETE http://localhost:4201/post/7a4fbaa7-a22e-492c-9e22-1ef4921dad8d
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiJmODNjZjQ3MC0xYjc1LTQ0ZWMtYWRiNy03ZDZjMGRlZWJkOGIiLCJpc0FkbWluIjpmYWxzZSwiZnVsbE5hbWUiOiJEaWFuYSBhYmVyaSIsImlhdCI6MTcwMjU4NjM0NSwiZXhwIjoxNzAyNjcyNzQ1fQ.q2f4tcavzwXBuyMrmusb7dioZ2oM3PqhzIQNkdXJHLA


### GETS ALL POSTS
GET http://localhost:4201/post
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiJmODNjZjQ3MC0xYjc1LTQ0ZWMtYWRiNy03ZDZjMGRlZWJkOGIiLCJpc0FkbWluIjpmYWxzZSwiZnVsbE5hbWUiOiJEaWFuYSBhYmVyaSIsImlhdCI6MTcwMjU4NjM0NSwiZXhwIjoxNzAyNjcyNzQ1fQ.q2f4tcavzwXBuyMrmusb7dioZ2oM3PqhzIQNkdXJHLA

### GETS ONE POST 
GET http://localhost:4201/post/9629028b-b4b8-4a2f-beef-d424a0b9dcbe
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiJmODNjZjQ3MC0xYjc1LTQ0ZWMtYWRiNy03ZDZjMGRlZWJkOGIiLCJpc0FkbWluIjpmYWxzZSwiZnVsbE5hbWUiOiJEaWFuYSBhYmVyaSIsImlhdCI6MTcwMjU4NjM0NSwiZXhwIjoxNzAyNjcyNzQ1fQ.q2f4tcavzwXBuyMrmusb7dioZ2oM3PqhzIQNkdXJHLA

### TOGGLE LIKE POST
POST http://localhost:4201/post/toggleLikePost
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiJmODNjZjQ3MC0xYjc1LTQ0ZWMtYWRiNy03ZDZjMGRlZWJkOGIiLCJpc0FkbWluIjpmYWxzZSwiZnVsbE5hbWUiOiJEaWFuYSBhYmVyaSIsImlhdCI6MTcwMjU4NjM0NSwiZXhwIjoxNzAyNjcyNzQ1fQ.q2f4tcavzwXBuyMrmusb7dioZ2oM3PqhzIQNkdXJHLA
Content-Type: application/json

{
    "post_id":"b9189814-4ca7-487e-bda5-422f8c2ee014",
    "user_id":"bd15993b-f1d5-4a44-8d5d-7d9f75d5d3a4"
}

### get Post Likes
GET http://localhost:4201/post/like/b9189814-4ca7-487e-bda5-422f8c2ee014
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJkaWFuYSIsImVtYWlsIjoiZGlhbmFhYmVyaTEyQGdtYWlsLmNvbSIsInVzZXJfaWQiOiJmODNjZjQ3MC0xYjc1LTQ0ZWMtYWRiNy03ZDZjMGRlZWJkOGIiLCJpc0FkbWluIjpmYWxzZSwiZnVsbE5hbWUiOiJEaWFuYSBhYmVyaSIsImlhdCI6MTcwMjU4NjM0NSwiZXhwIjoxNzAyNjcyNzQ1fQ.q2f4tcavzwXBuyMrmusb7dioZ2oM3PqhzIQNkdXJHLA

### get Post details
GET http://localhost:4201/post/details/c5df33cf-cd99-4aec-ac06-5a1766b23e05
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJpc2FhYyIsImVtYWlsIjoiaXNhYWNraWxpbW9AZ21haWwuY29tIiwidXNlcl9pZCI6IjkzMWJhNTFkLWJjYjQtNDc3MS05OTZjLWRmY2I1MzI1MzgxYyIsInByb2ZpbGVJbWFnZSI6Imh0dHBzOi8vaW1hZ2VzLnVuc3BsYXNoLmNvbS9waG90by0xNTE4MDIwMzgyMTEzLWE3ZThmYzM4ZWFjOT9xPTgwJnc9MTQzNCZhdXRvPWZvcm1hdCZmaXQ9Y3JvcCZpeGxpYj1yYi00LjAuMyZpeGlkPU0zd3hNakEzZkRCOE1IeHdhRzkwYnkxd1lXZGxmSHg4ZkdWdWZEQjhmSHg4ZkElM0QlM0QiLCJmdWxsTmFtZSI6IklzYWFjIEtpbGltbyIsImlhdCI6MTcwMjg4MjU3MiwiZXhwIjoxNzAyOTY4OTcyfQ.m42-mQfDQRtSnJEXWKn8H6fjR91CVh10TXaYKCdaHU8